@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Class "<<interface>>\nAddressBookStorage" as AddressBookStorage
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
Class JsonAdaptedTag
Class "<<interface>>\nJobsStorage" as JobsStorage
Class JsonJobsStorage
Class JsonSerializableJobList
Class JsonAdaptedJob
Class "<<interface>>\nApplicationStorage" as ApplicationStorage
Class JsonApplicationStorage
Class JsonSerializableApplicationList
Class JsonAdaptedApplication
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" AddressBookStorage
StorageManager -up-> "1" JobsStorage
StorageManager -up-> "1" ApplicationStorage

Storage -left-|> ApplicationStorage
Storage -left-|> JobsStorage
Storage -left-|> UserPrefsStorage
Storage -right-|> AddressBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

JsonJobsStorage .up.|> JobsStorage
JsonJobsStorage ..> JsonSerializableJobList
JsonSerializableJobList --> "*" JsonAdaptedJob

JsonApplicationStorage .up.|> ApplicationStorage
JsonApplicationStorage ..> JsonSerializableApplicationList
JsonSerializableApplicationList --> "*" JsonAdaptedApplication

@enduml
